apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-node-app
  template:
    metadata:
      labels:
        app: gitops-node-app
    spec:
      containers:
      - name: node-app
        image: ghcr.io/jenishcloudengineer/gitops-node-app:latest
        ports:
        - containerPort: 3000
