apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
